/* Automatic generated by './build/bin/build-entry.js' */

import Dropdown from './dropdown/index.js'
import DropdownItem from './dropdown-item/index.js'
import Loading from './loading/index.js'
import Uploader from './uploader/index.js'

const components = [
  Dropdown,
DropdownItem,
Loading,
Uploader
];

const version = '1.0.0'
const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });
  //
  // Vue.use(Loading.directive);
  //
  // Vue.prototype.$loading = Loading.service;
  // Vue.prototype.$msgbox = MessageBox;
  // Vue.prototype.$alert = MessageBox.alert;
  // Vue.prototype.$confirm = MessageBox.confirm;
  // Vue.prototype.$prompt = MessageBox.prompt;
  // Vue.prototype.$notify = Notification;
  // Vue.prototype.$message = Message;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

export {
  version,
  install,
  Dropdown,
DropdownItem,
Loading,
Uploader
};
