/* Automatic generated by './build/bin/build-entry.js' */

import Dropdown from '../components/dropdown/index.js'
import Loading from '../components/loading/index.js'
import Uploader from '../components/uploader/index.js'

const components = [
  Dropdown,
Loading,
Uploader
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;

  components.map(component => {
    Vue.component(component.name, component);
  });
  //
  // Vue.use(Loading.directive);
  //
  // Vue.prototype.$loading = Loading.service;
  // Vue.prototype.$msgbox = MessageBox;
  // Vue.prototype.$alert = MessageBox.alert;
  // Vue.prototype.$confirm = MessageBox.confirm;
  // Vue.prototype.$prompt = MessageBox.prompt;
  // Vue.prototype.$notify = Notification;
  // Vue.prototype.$message = Message;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

export default {
  version: '1.0.0',
  install,
  Dropdown,
  Loading,
  Uploader
}
